[package]
name = "fxtools"
version = "0.1.0"
edition = "2021"
documentation = "https://docs.rs/fxtools"
repository = "https://github.com/noamteyssier/fxtools"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fxread = "0.1"
clap = { version = "3", features = ["derive"] }
spinners = "4"
anyhow = "1"
