[package]
name = "fxtools"
version = "0.1.5"
edition = "2021"
description = "A collection of commandline Fasta/Fastq utility tools"
documentation = "https://docs.rs/fxtools"
repository = "https://github.com/noamteyssier/fxtools"
license = "MIT"
keywords = ["cli", "bioinformatics", "sequencing"]
categories = ["command-line-utilities", "science"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fxread = "0.1"
clap = { version = "3", features = ["derive"] }
spinners = { git = "https://github.com/noamteyssier/spinners", branch = "convert_stdout_to_stderr"}
anyhow = "1"
